  ---

# 
# https://github.com/prometheus/mysqld_exporter/releases/download/v0.10.0/mysqld_exporter-0.10.0.linux-amd64.tar.gz

  - set_fact:
      mysqld_exporter_sub_dir: "{{exporter_dir | default('mysqld_exporter')}}"
      mysqld_exporter_user: "{{exporter_user | default(prometheus_user)}}"
      mysqld_exporter_group: "{{exporter_group | default(prometheus_group)}}"

  - name: Prometheus | Create dirs
    file: path="{{item}}"  state=directory  owner="root"  group="{{ mysqld_exporter_group }}"   mode="u=rwx,g=rwx,o="
    become: yes
    with_items:
      - "{{prometheus_exporters_dir}}"
      - "{{prometheus_exporters_dir}}/{{mysqld_exporter_sub_dir}}"
    tags:
      - prometheus

  - name: Prometheus mysqld Exporter | Download distribution
    get_url:
      url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{prometheus_mysqld_exporter_version}}/mysqld_exporter-{{prometheus_mysqld_exporter_version}}.linux-amd64.tar.gz"
      dest: "{{prometheus_exporters_dir}}/mysqld_exporter-{{prometheus_mysqld_exporter_version}}.linux-amd64.tar.gz"
    become: yes
    become_user: "{{ mysqld_exporter_user }}"
    tags:
      - prometheus

  - name: Prometheus mysqld Exporter | unpack distribution
    unarchive:
      src: "{{prometheus_exporters_dir}}/mysqld_exporter-{{prometheus_mysqld_exporter_version}}.linux-amd64.tar.gz"
      dest: "{{prometheus_exporters_dir}}/{{mysqld_exporter_sub_dir}}"
      remote_src: yes
    become: yes
    become_user: "{{ mysqld_exporter_user }}"
    tags:
      - prometheus

  - name: Prometheus mysqld Exporter | link mysqld exporter dir
    file: src="{{prometheus_exporters_dir}}/{{mysqld_exporter_sub_dir}}/mysqld_exporter-{{prometheus_mysqld_exporter_version}}.linux-amd64" dest="{{mysqld_exporter_sub_dir}}/mysqld_exporter" owner="root"  group="{{ mysqld_exporter_group }}" state=link
    become: yes
    tags:
      - prometheus
