---

# https://github.com/google/cadvisor/releases
# https://github.com/google/cadvisor/releases/download/v0.27.4/cadvisor

  - set_fact:
      cadvisor_exporter_sub_dir: "{{exporter_config.exporter_dir | default('cadvisor_exporter')}}"
      cadvisor_exporter_user: "{{exporter_config.exporter_user | default(prometheus_user)}}"
      cadvisor_exporter_group: "{{exporter_config.exporter_group | default(prometheus_group)}}"

  - name: Prometheus | Create dirs
    file: path="{{current}}"  state=directory  owner="root"  group="{{ cadvisor_exporter_group }}"   mode="u=rwx,g=rwx,o="
    become: yes
    with_items:
      - "{{prometheus_exporters_dir}}/{{cadvisor_exporter_sub_dir}}"
    loop_control:
        loop_var: current
    tags:
      - prometheus

  - name: Prometheus cadvisor Exporter | Download distribution
    get_url:
      url: "https://github.com/google/cadvisor/releases/download/v{{prometheus_cadvisor_exporter_version}}/cadvisor"
      dest: "{{prometheus_exporters_dir}}/{{cadvisor_exporter_sub_dir}}/cadvisor-exporter"
      mode: "u=rwx,g=rx,o=rx"
    become: yes
    become_user: "{{ cadvisor_exporter_user }}"
    tags:
      - prometheus

  - include_tasks: "tasks_startup.yml exporter_startup_config={{exporter_config}}"
