---

#
# https://github.com/percona/mongodb_exporter/releases/download/v0.3.1/mongodb_exporter-0.3.1.linux-amd64.tar.gz

  - set_fact:
      mongodb_exporter_sub_dir: "{{exporter_config.exporter_dir | default('mongodb_exporter')}}"
      mongodb_exporter_user: "{{exporter_config.exporter_user | default(prometheus_user)}}"
      mongodb_exporter_group: "{{exporter_config.exporter_group | default(prometheus_group)}}"


  - name: Prometheus mongodb Exporter | Download distribution
    get_url:
      url: "https://github.com/percona/mongodb_exporter/releases/download/v{{prometheus_mongodb_exporter_version}}/mongodb_exporter-{{prometheus_mongodb_exporter_version}}.linux-amd64.tar.gz"
      dest: "{{prometheus_exporters_dir}}/mongodb_exporter-{{prometheus_mongodb_exporter_version}}.linux-amd64.tar.gz"
    become: yes
    become_user: "{{ mongodb_exporter_user }}"
    tags:
      - prometheus

  - name: Prometheus mongodb Exporter | unpack distribution
    unarchive:
      src: "{{prometheus_exporters_dir}}/mongodb_exporter-{{prometheus_mongodb_exporter_version}}.linux-amd64.tar.gz"
      dest: "{{prometheus_exporters_dir}}"
      remote_src: yes
    become: yes
    become_user: "{{ mongodb_exporter_user }}"
    tags:
      - prometheus

  - name: Prometheus mongodb Exporter | link mongodb exporter dir
    file: src="{{prometheus_exporters_dir}}/mongodb_exporter-{{prometheus_mongodb_exporter_version}}.linux-amd64/" dest="{{prometheus_exporters_dir}}/{{mongodb_exporter_sub_dir}}" owner="root"  group="{{ mongodb_exporter_group }}" state=link
    become: yes
    tags:
      - prometheus

  - include_tasks: "tasks_startup.yml exporter_startup_config={{exporter_config}}"    
