---

# https://github.com/prometheus/node_exporter/releases/download/0.12.0/node_exporter-0.12.0.linux-amd64.tar.gz

  - set_fact:
      node_exporter_sub_dir: "{{exporter_config.exporter_dir | default('node_exporter')}}"
      node_exporter_user: "{{exporter_config.exporter_user | default(prometheus_user)}}"
      node_exporter_group: "{{exporter_config.exporter_group | default(prometheus_group)}}"

  - name: Prometheus Node Exporter | Download distribution
    get_url:
      url: "https://github.com/prometheus/node_exporter/releases/download/v{{prometheus_node_exporter_version}}/node_exporter-{{prometheus_node_exporter_version}}.linux-amd64.tar.gz"
      dest: "/tmp/{{prometheus_exporters_dir}}/node_exporter-{{prometheus_node_exporter_version}}.linux-amd64.tar.gz"
    become: yes
    become_user: "{{ node_exporter_user }}"
    tags:
      - prometheus

  - name: Prometheus Node Exporter | unpack distribution
    unarchive:
      src: "/tmp/{{prometheus_exporters_dir}}/node_exporter-{{prometheus_node_exporter_version}}.linux-amd64.tar.gz"
      dest: "{{prometheus_exporters_dir}}"
      remote_src: yes
    become: yes
    become_user: "{{ node_exporter_user }}"
    tags:
      - prometheus

  - name: Prometheus Node Exporter | link node exporter dir
    file: src="{{prometheus_exporters_dir}}/node_exporter-{{prometheus_node_exporter_version}}.linux-amd64/" dest="{{prometheus_exporters_dir}}/{{node_exporter_sub_dir}}" owner="root"  group="{{ node_exporter_group }}" state=link
    become: yes
    tags:
      - prometheus

  - debug: var="exporter_config"

  - include_tasks: "tasks_startup.yml exporter_startup_config={{exporter_config}}"
